[build]
  command = "yarn comments:get; bundle exec rake build:generate; bundle exec rake test; yarn run lambda:build"
  publish = "_site"
  functions = "lambda"

[context.branch-deploy]
  command = "yarn comments:get; bundle exec rake build:generate[integ]; yarn run lambda:build"

[dev]
  command = "bundle exec rake"
  port = 10443
  publish = "_site"
