[build]
  command = "npm run comments:get; npm run bookmarks:get; bundle exec rake build:generate; bundle exec rake test; npm run lambda:build"
  publish = "_site"
  functions = "lambda"

[context.branch-deploy]
  command = "npm run comments:get; npm run bookmarks:get; bundle exec rake build:generate[integ]; npm run lambda:build"

[dev]
  command = "bundle exec rake"
  port = 10443
  publish = "_site"
